### ISSUE TITLE
기여 프로젝트 선정

### ISSUE THREAD

**Issue by devAdaid** [17-1-SKKU-OSS/126B#4]
참여할만한 프로젝트 찾은것들 모두 댓글로 달아본 후 결정해 봅시다

**Comment by devAdaid** [comment]
https://github.com/beetbox/beets

**Comment by mandarin4452** [comment]
https://github.com/facebookresearch/ParlAI

**Comment by devAdaid** [comment]
https://github.com/bjorn/tiled

**Comment by devAdaid** [comment]
5/16일 Tiled 번역하기로 결정.
